### ISSUE TITLE
Compile GTEST directly in the CMakeFIles

### ISSUE THREAD

**Issue by MaxNoe** [tudo-astroparticlephysics/PROPOSAL#10]
This would remove the compilation on Ubuntu.

See https://cmake.org/cmake/help/v3.0/module/FindGTest.html

**Comment by twelvemd12** [comment]
Fixed with the release https://github.com/tudo-astroparticlephysics/PROPOSAL/tree/4.1.0.
Google Test is now part of the project, therefore no system wide or separate installation is needed.
