### ISSUE TITLE
Scientific question: Can I calculate Cherenkov photons generation with PROPOSAL?

### ISSUE THREAD

**Issue by Adiolph** [tudo-astroparticlephysics/PROPOSAL#105]
Hi:
I am wondering if I can use `PROPOSAL` to calculate the Cherenkov photon production of muon and its secondaries.
`PROPOSAL` can calculate the secondary particles produced by muon along its track, which greate because those secondary particles can also produce Cherenkov lights. 

My main concerns is that if I set energy cut for the secondaries production, the low energy secondaries which are classified as continous energy loss will no longer be tracked. However, those low energy secondaries will contribute to Cherenkov photon production in real physics world. 

Do you have any suggestions?

**Comment by sudojan** [comment]
Well, it depends ... how accurate do you want to simulate your Cherenkov photons?
For a rough estimation, one can assume that the amount of Cherenkov photons goes linear with the particle energy and just use the continuous and stochastic losses from PROPOSAL.
For an accurate description of Cherenkov Photons, e.g. from Air Showers the framework CORSIKA would be the place to look at. The development version is even using PROPOSAL for em-propagation.

**Comment by Adiolph** [comment]
Thanks for replay!
Your suggestion is very helpful. I will try simple parameterization method (as a function of particle energy) to generate Cherenkov photons from particles.
I am not familiar with Fortran language, so I suppose I have to wait until CORSIKA 8 is developed.

**Comment by MaxNoe** [comment]
@Adiolph You do not have to know FORTRAN to *use* CORSIKA for Cherenkov Light Production.

Actually, the Cherenkov part of CORSIKA (the iact/atmo extension) is written in C.

See: https://www.mpi-hd.mpg.de/hfm/bernlohr/iact-atmo/
