### ISSUE TITLE
direction value outside the allowed range

### ISSUE THREAD

**Issue by pkalaczynski** [tudo-astroparticlephysics/PROPOSAL#119]
There seems to be a problem with how the directional cosines are evaluated. I have a muon track, which before the propagation step in the simulation chain has the directional cosines:
```
dir.x            dir.y            dir.z
-0.200238   -0.046389   -0.978648
```
 but after propagating with PROPOSAL it ends up to be:
```
dir.x            dir.y            dir.z
0.0086624  -0.004045   -1.000020
```

which of course does not make sense, since cos should not give anything smaller than -1.0 ...

I suppose it could be just some precision issue, but I'm not so familiar with the source code, so it's hard for me to judge where could things go wrong.

**Comment by Jean1995** [comment]
Since the direction should be a unit vector, it is indeed wrong that the z component is smaller than -1.0...

Could you provide the energies of the propagation step, i.e. the energies before and after the propagation step when the direction became invalid? Can you also provide the Scattering Model, the energy cut settings and the medium you used?

I have an idea where the origin of this error might be, but I would like to be able to reproduce your error to see if I am right.

**Comment by pkalaczynski** [comment]
PROPOSAL version: 6.1.4

E before propagation: 668.503 GeV
E after propagation:    0.7800031 GeV

Scattering model: HighlandIntegral
Energy cuts: default value used

Medium:
Sea water:
Sea rock:

water composition:
```
  shared_ptr<const PROPOSAL::Medium> med_sw = make_shared<const PROPOSAL::Medium>("gSeaWater",
           1,
           75.0,    // I
           -3.5017, // C
           0.09116, // a
           3.4773,  // m
           0.2400,  // X0
           2.8004,  // X1
           0,       // d0
          RhoSW, // massDensity
           ComponentSW);

RhoSW = 1.03975

ComponentSR.push_back(PROPOSAL::Components::Component(AtomName[iComp].c_str(),Z[iComp],AtomMass[iComp],AtomInMolecule));
```

with the following values

```
H 1 1.00783 2.00048
C 6 12 4.34779e-05
O 8 15.9949 1
Na 11 22.9898 0.00875349
Mg 12 23.985 0.00100372
S 16 31.9721 0.00053035
Cl 17 34.9689 0.0103374
K 19 38.9637 0.00019129
Ca 20 39.9626 0.000186508
Br 35 79.9185 1.56214e-05
```

**Comment by pkalaczynski** [comment]
I hope this helps. If this is not enough, I can try to dig in the propagation algorithm and extract the values for the exact step when it goes wrong (we typically call PROPOSAL several times)

**Comment by Jean1995** [comment]
Did you give this initial condition of `E = 668.503 GeV` and a direction of `(-0.200238, -0.046389, -0.978648)` to PROPOSAL, or is this an intermediate value that you took from the PROPOSAL output?

**Comment by pkalaczynski** [comment]
That's the initial condition (muon from CORSIKA at sea level)

**Comment by Jean1995** [comment]
I discovered that PROPOSAL does not automatically calculate the spherical coordinates of the direction vector before sampling the multiple scattering for the first time during Propagation, although the spherical coordinates of the direction vector are needed.

I strongly assume that this could be the reason behind this bug.

Could you try to manually force the direction object to calculate the spherical coordinates after initialization of the initial state?
You can do this in Python by simply calling
`dir.spherical_from_cartesian()`
or in C++ by calling
`dir.CalculateSphericalCoordinates()`
just after initializing the initial particle direction.

If my idea is correct, this should fix the issue.

**Comment by pkalaczynski** [comment]
It does fix it indeed! Now there's no more incorrect direction value.
