### ISSUE TITLE
photohadronic loss model addition

### ISSUE THREAD

**Issue by ibsafa** [tudo-astroparticlephysics/PROPOSAL#125]
An updated parameterization of the F2 functions based on fits to HERA data was made available in 2013. This description fits recent data better, and would be a great addition to the available models in PROPOSAL. 

The parameterization is very similar to the ALLM97 model, the only changes being the values of the fit parameters, see https://arxiv.org/pdf/1302.6119.pdf Eq. 2 for the F2 function, and Table 1. for the fitted parameter values.

**Comment by asandrock** [comment]
Hi Ibrahim, this parametrization is in fact rather different from ALLM97, which you can see for instance from the fact that this parametrization contains 7 parameters, while the ALLM parametrization has 23. Moreover, this parametrization diverges for Q^2 -> 0, which seems problematic for use in PROPOSAL, as the minimum value of Q^2 is small.

There actually has been an update on the ALLM parametrization in Abt et al. (2017) [https://doi.org/10.1103/PhysRevD.96.014001] which really only changes the values of the fit parameters (Table VIII). Would you be satisfied if we implemented this model instead, or are you specifically looking for a parametrization that saturates the Froissart bound?

**Comment by ibsafa** [comment]
Hi Alex 
Sorry I should have been clearer. What I meant by similar is that the implementation of this model, in terms of integration limits etc. in the code, is the same, the only difference being the F2 function. So it’s just a matter of coding these parameters in and calling the new F2 function. I’ve implemented this model in MMC as described and it works well. I have also checked it against an independent analytic calculation of the losses according to this model.
As for the divergence, this model specifically deals with small x, large Q^2 where the ALLM parametrization diverges, so they are complementary. 

We are using this for extremely high energy taus, where losses become dominant and the photohadronic losses in particular take over. Using this model vs. ALLM shows a factor of ~2 change in the range at high energies so it’s important to have both of them when doing calculations in this energy range.

**Comment by asandrock** [comment]
I calculated the average energy loss for muons and taus with this parametrization, with ALLM 97 and with the newer parametrizations by Abt et al. The average energy loss is absurdly high, as I expected for a parametrization that diverges for Q^2 -> 0. There is a newer paper by Block et al. from 2014 [http://dx.doi.org/10.1103/PhysRevD.89.094027], where they use a parametrization that smoothly connects to the photoabsorption cross section parametrization from Block & Halzen (2004). I have shown this parametrization below as BDH; I have taken only the asymptotic component into account and ignored the valence quarks.
![muon2](https://user-images.githubusercontent.com/37806666/109776210-66737e80-7c13-11eb-9dfd-61fd671d9262.png)
![tau2](https://user-images.githubusercontent.com/37806666/109776213-670c1500-7c13-11eb-9977-b7268176953d.png)

Cutting away the large losses of the Block et al. (2013) parametrization (which was not designed to be valid in the region of very small Q^2 << 1 GeV^2), the ALLM97, HHT-ALLM-FT and BDH parametrization are rather similar, while the HHT-ALLM (i.e. the refit of the ALLM parametrization using only the combined HERA data, but without fixed-target data) is noticeably larger.
![muon](https://user-images.githubusercontent.com/37806666/109776205-65425180-7c13-11eb-940c-f529a20ea8bc.png)![tau](https://user-images.githubusercontent.com/37806666/109776211-66737e80-7c13-11eb-80c2-3c9ff777b025.png)

**Comment by ibsafa** [comment]
I sincerely apologize, i just checked my code and the parameters I'm using match the ones from the paper you label BDH. I must have linked the wrong paper to you. 
You are right, "block" is just absurdly high. again i'm sorry and thanks for looking into it carefully. Apart from my blunder, this is looking great! So will both the new ALLM and BDH be included in proposal moving forward?

**Comment by ibsafa** [comment]
Just another quick comment after looking closely at your plot, i agree ALLM97 and BDH are rather similar up to several PeV, and that's expected. they should diverge from each other very slowly, and the differences are expected to manifest near the EeV energy range

**Comment by asandrock** [comment]
I noticed, that I forgot a factor v in the program that produced the plots above, so they actually show the total inelastic cross section in uncommon units instead of the average energy loss (I did not do those plots with PROPOSAL, I just quickly cobbled together a program to do the numerical integration). The energy loss with the Block (2013) parametrization is still absurdly large, but the differences between ALLM97, HHT-ALLM-FT, HHT-ALLM and BDH are somewhat larger.
![muon2](https://user-images.githubusercontent.com/37806666/109963805-dfe79b80-7cfd-11eb-8570-e94dc02f4441.png)
![tau2](https://user-images.githubusercontent.com/37806666/109963824-e544e600-7cfd-11eb-91dc-e3641fbd3572.png)

I incline not to implement HHT-ALLM, because it not only diverges significantly from the others but also has a weird photoabsorption limit, which is clearly at odds with the well-known measurements from SLAC:
![sigma_gp](https://user-images.githubusercontent.com/37806666/109963862-f2fa6b80-7cfd-11eb-9cc2-1ed4c082c968.png)

**Comment by sudojan** [comment]
Done in PR #128
