### ISSUE TITLE
Linker warnings when building with python on MacOS

### ISSUE THREAD

**Issue by sudojan** [tudo-astroparticlephysics/PROPOSAL#141]
When installing PROPOSAL with the `BUILD_PYTHON` option, tons of warnings arise when
`Linking CXX shared library proposal.cpython-38-darwin.so`

which looks like
`ld: warning: direct access in function 'init_components(pybind11::module_&)' from file '/tmp/lto.o' to global weak symbol 'PROPOSAL::Component::GetName() const' from file '../PROPOSAL/libPROPOSAL.a(Components.cxx.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.`
or
`ld: warning: direct access in function '___cxx_global_var_init.82' from file '/tmp/lto.o' to global weak symbol 'PROPOSAL::transform_loss<PROPOSAL::crosssection::PhotoPairTsai>::func' from file '../PROPOSAL/libPROPOSAL.a(Propagator.cxx.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.`

this wasn't the case when the visibility mode was set, which was removed [here](https://github.com/tudo-astroparticlephysics/PROPOSAL/commit/188d2a9352212e3e502609400afb26633c2446a5) to face issues for the conan-center [PR](https://github.com/conan-io/conan-center-index/pull/5149)

however, when installing PROPOSAL as explained the `Install.md` on a MacOS, this problem arises and is extremely annoying with thousands of lines of warnings.

**Comment by MaxSac** [comment]
@sudojan is this problem adequately solved with the commit?
