### ISSUE TITLE
CI Tests on MacOS

### ISSUE THREAD

**Issue by sudojan** [tudo-astroparticlephysics/PROPOSAL#143]
There are some/many users, who are using PROPOSAL on a MacOS.
Therefore a build on MacOS should be included in the CI.
Some MacOS related issues could have also been identified earlier.
Shouldn't be too difficult adding this on travis.

**Comment by maxnoe** [comment]
It isn't difficult,  but expensive on Travis.

As discussed some time ago with @MaxSac , due to the pricing changes on Travis, you should switch to using github actions instead, which also offers macos builds.

**Comment by Jean1995** [comment]
Maybe we can also provide a Windows build there, which is not that well supported by Travis at the moment.
