### ISSUE TITLE
Standalone installation seems to still require icetray

### ISSUE THREAD

**Issue by Kakiczi** [tudo-astroparticlephysics/PROPOSAL#16]
I have installed following the instructions for standalone install, but then when I try doing 

`#include "PROPOSAL/PROPOSAL.h"`

I get:

```
In file included from /usr/local/include/PROPOSAL/PROPOSAL.h:104,
                 from test.cpp:2:
/usr/local/include/PROPOSAL/Output.h:50:14: fatal error: icetray/I3Logging.h: No such file or directory
     #include <icetray/I3Logging.h>
              ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by Jean1995** [comment]
This issue has recently been fixed, you should be able to use PROPOSAL as a Standalone installation.

After following the instructions for installation, your program should compile with
`g++ test.cpp -std=c++11 -lPROPOSAL` now.

Thank you for the report!
