### ISSUE TITLE
Muon after propagation with less energy than its rest energy?

### ISSUE THREAD

**Issue by pkalaczynski** [tudo-astroparticlephysics/PROPOSAL#201]
When I used PROPOSAL in my code I got a muon with E=0.0114306 GeV:

```
track.PdgCode: -13
track.E: 0.0114306
kMuonMass: 0.105658
```

Is the particle energy in PROPOSAL the total or kinetic energy? If it's the total energy, then there should be a check if it's not below the particle mass and if so, the energy should be clipped to the rest mass.

**Comment by Jean1995** [comment]
Particle energies in PROPOSAL are total energies, so for muons the energy should indeed not be below the rest mass.

Which version of PROPOSAL are you using? Could you explain in more detail what you have been doing, or even post a code example that reproduces the issue? Did this happen regularly, or has this been a rare case?

**Comment by pkalaczynski** [comment]
I'm using `v6.1.5` to propagate muons down through sea water:

```
          PROPOSAL::DynamicData particle_mu(PROPOSAL::MuMinusDef::Get().particle_type);

          particle_mu.SetEnergy(track.E*1E3); // [MeV]
          particle_mu.SetPropagatedDistance(0);
          particle_mu.SetPosition(PROPOSAL::Vector3D(track.V1*1E2,track.V2*1E2,track.V3*1E2));
          particle_mu.SetDirection(direction);

          particle_mu.SetTime(track.T);

          PROPOSAL::Secondaries sec = ProposalMu->Propagate(particle_mu,DepthW*100.);

          trackf->E=sec.GetEnergy().back()/1.E3;
          trackf->V1=sec.GetPosition().back().GetX()/1.E2;
          trackf->V2=sec.GetPosition().back().GetY()/1.E2;
          trackf->V3=sec.GetPosition().back().GetZ()/1.E2;

          trackf->D1=sec.GetDirection().back().GetX();
          trackf->D2=sec.GetDirection().back().GetY();
          trackf->D3=sec.GetDirection().back().GetZ();

          trackf->T=sec.GetTime().back();
```

I'm just posting a snippet as the whole code is quite huge.

I's not really rare, seems to happen a lot.

**Comment by Jean1995** [comment]
Did you check that the last particle in the list is still a muon? The muon may have decayed, in this case, `sec.GetEnergy().back()` will return the energy of one of the decay products (which can be smaller than the muon mass).

**Comment by pkalaczynski** [comment]
Hmm, this could be what's causing the problem, the code just assumes it's a muon the whole time. I will check.

**Comment by pkalaczynski** [comment]
I tried to use `GetTrackTypes()` but got
```
error: 'class PROPOSAL::Secondaries' has no member named 'GetTrackTypes'
```
even though I see it's defined in `src\PROPOSAL\PROPOSAL\Secondaries.h` ...

Maybe I'm just doing it wrong. I tried:
```
ProposalMu = new PROPOSAL::Propagator(PROPOSAL::MuMinusDef::Get(), sectors, geoCan);
PROPOSAL::Secondaries sec = ProposalMu->Propagate(particle_mu,DepthW*100.);
cout << " sec.GetTrackTypes().back():" << sec.GetTrackTypes().back() <<endl;
```

**Comment by Jean1995** [comment]
> I tried to use `GetTrackTypes()` but got

The `GetTrackTypes()` method is only available in PROPOSAL 7.x.x

For PROPOSAL 6.1.5, you need to do something like:
`cout << sec.GetSecondaries().back().GetType() << endl;`

**Comment by pkalaczynski** [comment]
Ah, that's why it didn't work, thanks!

It seems that these are indeed mostly decay/interaction products:
```
E:      0.0281696        Type:  -820500953
E:      0.0299018        Type:  1000000004
E:      0.0440194        Type:  1308652133
E:      0.0474503        Type:  1000000004
E:      0.0384809        Type:  -1922854096
E:      0.017413         Type:  1000000004
E:      0.000645503      Type:  1000000003
E:      0.0329   Type:  1000000003
E:      0.0290153        Type:  1000000004
E:      0.0196181        Type:  1000000003
E:      0.0087395        Type:  1000000004
E:      0.0266835        Type:  1000000003
E:      0.00799436       Type:  1000000003
E:      0.0366201        Type:  1000000003
E:      0.0407166        Type:  -1760831753
E:      0.0101898        Type:  -1693156703
E:      0.0525619        Type:  1000000003
E:      0.024282         Type:  1000000003
E:      0.0197449        Type:  11
E:      0.0157854        Type:  1000000003
E:      0.0411973        Type:  -12
E:      0.0185   Type:  1000000003
E:      0.0225484        Type:  1000000004
E:      0.0205432        Type:  14
E:      0.0480498        Type:  1000000004
E:      0.0140255        Type:  -12
E:      0.0135829        Type:  1000000003
E:      0.0326845        Type:  1000000004
E:      0.0368984        Type:  1000000003
E:      0.044322         Type:  1000000004
E:      0.0467649        Type:  -12
E:      0.0245677        Type:  1000000003
E:      0.0429953        Type:  -12
E:      0.0408371        Type:  -12
E:      0.0351075        Type:  -321935432
E:      0.0402317        Type:  18
E:      0.0496045        Type:  1000000004
E:      0.00918402       Type:  1000000003
E:      0.0122849        Type:  1000000003
```

But not only, I did find some muons as well!:

```
E:      0.0296143        Type:  13
E:      0.0489773        Type:  13
E:      0.0491198        Type:  13
```

I did it with:
```
          if ((sec.GetEnergy().back()/1.E3<kMuonMass) && (abs(sec[sec.GetEnergy().size()].GetType())==13)) { // is not allo
            cout << "E:\t" << trackf->E << "\t Type:\t" << sec[sec.GetEnergy().size()].GetType() <<endl;
          }
```

**Comment by Jean1995** [comment]
You need to be careful here, `sec[sec.GetEnergy().size()].GetType()` is not defined, since `size()` returns the size of the vector, but index counting starts at zero (so you are trying to access an object outside the array).

That's probably the reason why you get weird types such as `-1760831753` or `18`

**Comment by pkalaczynski** [comment]
I tried `.back()` but it didn't work hmm maybe I forgot about `.GetSecondaries()` first. I will check.

**Comment by maxnoe** [comment]
@pkalaczynski 

This should work for you, right?

```
for (const auto& secondary: sec.GetSecondaries()) {
    std::cout <<"Type: " << secondary.GetType() << ", Energy: " << secondary.GetEnergy() << '\n';
}
```

**Comment by pkalaczynski** [comment]
Alright, now if I check for `(sec.GetEnergy().back()/1.E3<kMuonMass) && (abs(sec.GetSecondaries().back().GetType())==13)` I don't get anything as I should.

If I just loop over secondaries for each propagated muon, as @maxnoe suggested, I get stuff like:
```
Type: 1000000008, Energy: 103769
Type: 1000000008, Energy: 102504
Type: 1000000008, Energy: 101239
Type: 1000000008, Energy: 99973.7
Type: 1000000008, Energy: 99961
```
or
```
Type: 11, Energy: 51.0915
Type: 14, Energy: 7.29421
Type: -12, Energy: 47.2726
```

So it seems it was indeed not a bug in PROPOSAL, but me not using it properly 😅. 

Thank you a lot for your help! I am closing the issue.

**Comment by maxnoe** [comment]
> (sec.GetEnergy().back()/1.E3<kMuonMass) && (abs(sec.GetSecondaries().back().GetType())==13)

Just a note: this is very inefficient. `GetEnergy` creates a new vector of the secondary energies for you and `GetSecondaries` also returns a copy. 

That's not ideal. There is `GetModifiableSecondaries`, which returns a reference to the underlying vector, so does not make copies.

**Comment by pkalaczynski** [comment]
Thanks for the tip @maxnoe ! :)
