### ISSUE TITLE
Test if a Muon has Decayed?

### ISSUE THREAD

**Issue by wjwoodley** [tudo-astroparticlephysics/PROPOSAL#206]
I am trying to use PROPOSAL v7.0.7 to figure out if a propagated muon has decayed or not. If it has not decayed, then I want to record its final energy. What is the simplest way of doing this? I am using the code below to propagate a 0.1 TeV muon 1 km through standard rock.

```
import proposal as pp

args = {
    "particle_def": pp.particle.MuMinusDef(),
    "target": pp.medium.StandardRock(),
    "interpolate": True,
    "cuts": pp.EnergyCutSettings(500, 1, True)
    }

cross_sections = pp.crosssection.make_std_crosssection(**args)

collection = pp.PropagationUtilityCollection()
collection.interaction = pp.make_interaction(cross_sections, True)
collection.displacement = pp.make_displacement(cross_sections, True)
collection.time = pp.make_time(cross_sections, args["particle_def"], True)
collection.decay = pp.make_decay(cross_sections, args["particle_def"], True)

utility = pp.PropagationUtility(collection = collection)

detector = pp.geometry.Sphere(position = pp.Cartesian3D(0, 0, 0), radius = 100000, inner_radius = 0)
density_distr = pp.density_distribution.density_homogeneous(2.65)

propagator = pp.Propagator(args["particle_def"], [(detector, utility, density_distr)])

init_state = pp.particle.ParticleState()
init_state.position = pp.Cartesian3D(0, 0, 0)
init_state.direction = pp.Cartesian3D(0, 0, 1)
init_state.energy = 1e5 # MeV

# Propagate the muon

pp.RandomGenerator.get().set_seed(500)

track = propagator.propagate(init_state, 1e5)

# Print decay products

print(track.track_energies())
print(track.decay_products())
```

The output is the following:

```
[100000.0, 94083.19481330515, 89305.712939157, 81413.50545314988, 80788.67982923005, 61550.366224627236, 57931.98353745115, 17841.321649920672, 17299.51925144831, 105.6583745]
[]
```

How should the last step be interpreted, where the muon loses the rest of its kinetic energy? Does this suggest a decay happens after this step, or does the propagation simply stop here? The list of decay products is empty, suggesting no decay, so do I have to turn something on other than putting `pp.make_decay()` in order for this to be filled?

**Comment by Jean1995** [comment]
> If [the muon] has not decayed, then I want to record its final energy. What is the simplest way of doing this?

Using `track.track_types()[-1]` on a track, you can check for the type of the last interaction of the propagation. If this is equal to `pp.particle.Interaction_Type.decay`, you know that the muon decayed during propagation. Otherwise, you can get the final muon energy using `track.track_energies()[-1]`.
You can do something like this:

```
final_energy = []
stat = 10000
for i in range(stat):
    track = propagator.propagate(init_state, 1e5)
    if(track.track_types()[-1] != pp.particle.Interaction_Type.decay):
        final_energy.append(track.track_energies()[-1])
```

Note that for this script, most/all of the final energies are equal to the muon rest mass, which means that the muon has been propagated until it lost all its energy. 

> How should the last step be interpreted, where the muon loses the rest of its kinetic energy? Does this suggest a decay happens after this step, or does the propagation simply stop here? The list of decay products is empty, suggesting no decay, so do I have to turn something on other than putting pp.make_decay() in order for this to be filled?

Yes, if the muon lost all its kinetic energy during the last step, the muon did not decay during propagation and the propagation has been stopped. The command `pp.make_decay()` will create the decay products only if the muon decayed during the propagation.

**Comment by wjwoodley** [comment]
Ok, I understand now. That's very helpful, thank you!
