### ISSUE TITLE
Secondaries array is not correctly passed to a function in the Python wrapper

### ISSUE THREAD

**Issue by daniel-zid** [tudo-astroparticlephysics/PROPOSAL#25]
I'm having trouble if I pass a secondaries array to a function, so I'm going to show a simplified version of my code. Let's us assume that I propagate a particle and store the secondaries in an array:

`secondaries = propagator.propagate(propagation_length)`

And then I pass this array to a function that loops over the secondaries and prints their x coordinate.

`def print_x_secondaries(secondaries):
    for sec in secondaries:
        print(sec.position.x)`

`print_x_secondaries(secondaries)`

I get the error: 
> NameError: name 'x' is not defined,

while if I don't call the function and loop directly, the x coordinates are correctly accessed. Any idea of what is going on? Thank you.

**Comment by MaxNoe** [comment]
This cannot be the code raising the error,  if it really did not find `position.x` you'd get an attribute error. 

Can you provide the actual code?

**Comment by daniel-zid** [comment]
Sure thing. This is the function that I use for propagating:

`def get_secondaries_array(energy_leptons, lepton_codes, lepton_positions = None, lepton_directions = None,
                        random_seed=None, config_file='SouthPole'):

    low = 0.1*pp_PeV # Low energy limit for the propagating particle
    propagation_length = 1000*pp_km # Maximum propagation length
    compact_dist = 10*pp_m # Maximum distance for the compact losses
    min_energy_loss = 1*pp_PeV # Minimal energy for a selected secondary-induced shower

    if random_seed == None:
        random_seed = int( np.random.uniform(0,1e8) )

    propagators = {}
    for lepton_code in np.unique(lepton_codes):
        if lepton_code not in propagators:
            propagators[lepton_code] = create_propagator(low=low, particle_code=lepton_code,
                                                         config_file=config_file)

    secondaries_array = []

    if lepton_positions is None:
        lepton_positions = [(0, 0, 0)] * len(energy_leptons)
    if lepton_directions is None:
        lepton_directions = [(0, 0, -1)] * len(energy_leptons)

    for energy_lepton, lepton_code, lepton_position, lepton_direction in zip(energy_leptons,
        lepton_codes, lepton_positions, lepton_directions):

        x, y, z = lepton_position
        px, py, pz = lepton_direction
        propagators[lepton_code].particle.position = pp.Vector3D(x, y, z)
        propagators[lepton_code].particle.direction = pp.Vector3D(px, py, pz)
        propagators[lepton_code].particle.propagated_distance = 0
        propagators[lepton_code].particle.energy = energy_lepton / units.MeV # Proposal's energy unit is the MeV

        secondaries = propagators[lepton_code].propagate(propagation_length)

        shower_inducing_prods = filter_secondaries(secondaries, min_energy_loss)`

There are more instructions, but they're irrelevant since the code crashes. This is the function that crashes:

`def filter_secondaries(secondaries, min_energy_loss):

    shower_inducing_prods = []

    for sec in secondaries:

        # Decays contain only one shower-inducing particle
        # Muons and neutrinos resulting from decays are ignored
        if produces_shower(sec, min_energy_loss): # Here produces_shower can be True, it does not matter

            distance  = ( (sec.position.x - x) * units.cm )**2
            distance += ( (sec.position.y - y) * units.cm )**2
            distance += ( (sec.position.z - z) * units.cm )**2
            distance  = np.sqrt(distance)
            energy = sec.energy * units.MeV

            shower_type, code, name = shower_properties(sec)

            shower_inducing_prods.append( SecondaryProperties(distance, energy, shower_type, code, name) )

    return shower_inducing_prods`

And this is the error I get:
>shower_inducing_prods = filter_secondaries(secondaries, min_energy_loss)
  File "/mnt_afs/NuRadioMC/NuRadioMC/EvtGen/NuRadioProposal.py", line 291, in filter_secondaries
    distance  = ( (sec.position.x - x) * units.cm )**2
NameError: name 'x' is not defined

If you want to run the exact same code, I will have to upload it, maybe to a new NuRadioMC (our radio code) branch.
