### ISSUE TITLE
Inconsistency of the ordering of positional parameters in geometry.Cylinder with the corresponding named parameters.

### ISSUE THREAD

**Issue by Martin-SF** [tudo-astroparticlephysics/PROPOSAL#263]
When using proposal.geometry.cylinder in python, I always assumed from my work with the json files, that the positional parameters are in the same ordering as in the json file when calling
`pp.geometry.Cylinder(pp.Cartesian3D((0, 0, 0)), 50, 60, 10)`.
 
I assumed that it sets `inner_radius `to 50, `outer_radius `to 60 and `height `to 1.
But after checking the c++ files the ordering of the parameters is different `(const Vector3D& position, double z, double radius, double inner_radius). `
Maybe it could be made a bit more intuitive. Like swapping the positional parameters in the pybinding.

Also, the `pbdoc` of the named parameters in the pybinding files suggests this order.

```
    py::class_<Cylinder, std::shared_ptr<Cylinder>, Geometry>(m_sub, "Cylinder",
                                                              R"pbdoc(
                A cylinder can be created as a hollow cylinder.
                For this purpose, a corresponding radius must be
                selected for the bore along the main axis. A
                cylinder without a bore is equal to a bore radius
                equal to zero.
            )pbdoc")
        .def(py::init<const Vector3D&, double, double, double>())
        .def(py::init<const Cylinder&>())
        .def_property("inner_radius", &Cylinder::GetInnerRadius,
                      &Cylinder::SetInnerRadius,
                      R"pbdoc(
                the inner radius of the bore through the main axis
                of the cylinder
            )pbdoc")
        .def_property("radius", &Cylinder::GetRadius, &Cylinder::SetRadius,
                      R"pbdoc(
                radius of outer shell of the cylinder
            )pbdoc")
        .def_property("height", &Cylinder::GetZ, &Cylinder::SetZ,
                      R"pbdoc(
                height of the cylinder
            )pbdoc");

```

**Comment by maxnoe** [comment]
JSON objects are defined to be unordered, so you shouldn't put any meaning into the order of things there. 

What should be done however is adding support for keyword arguments in the python bindings.
Edit: I did it here: #264 

Also: an inner radius larger than the outer radius should raise an exception, right?
It only logs.

**Comment by Jean1995** [comment]
> Also: an inner radius larger than the outer radius should raise an exception, right? It only logs.

This currently logs, but also switches the inner radius and outer radius so that the outer radius is always larger than the inner radius.

**Comment by Jean1995** [comment]
I would agree with Max that this is rather a problem of an incomplete documentation.
