### ISSUE TITLE
Unexpected increase in muon range

### ISSUE THREAD

**Issue by pkalaczynski** [tudo-astroparticlephysics/PROPOSAL#268]
Hi!

I wanted to test what muon range can I expect from `PROPOSAL 6.1.5`, so I shot muons through 100km of sea water to be sure they will stop before exiting. I plotted the reached distance as a function of the initial muon energy:
![muon_range](https://user-images.githubusercontent.com/25057504/157468643-4ce2d357-3737-4766-8cb3-145a97e7fb3d.png)

What I found surprising and possibly unphysical is the rise at the highest energies (`~10^11GeV`). Is there any reason why the range slope could increase there? I'd rather expect it to further decrease, if anything.

Cheers,
Piotr

**Comment by asandrock** [comment]
At such extremely high energies, the Landau-Pomeranchuk-Migdal effect and the Ter-Mikaelian effect decrease the Bremsstrahlung cross section noticeably. If you plot the average energy loss divided by the energy, it becomes clear:
![loss_muon](https://user-images.githubusercontent.com/37806666/157478043-7f18d137-e3fe-4158-b5cf-5bc493cc1116.png)

**Comment by maxnoe** [comment]
What are those horizontal stripes in your histogram?

**Comment by pkalaczynski** [comment]
> What are those horizontal stripes in your histogram?

It's my sampling: I've been propagating in `100m` (`10^-1km`) steps

**Comment by pkalaczynski** [comment]
> interpolation



> max_node_energy

Thanks @Jean1995 , I indeed have `"max_node_energy" : 1e14,`. I do not really expect that high muon energies, so I suppose I'll just clip at `1e14 MeV`.

**Comment by pkalaczynski** [comment]
> At such extremely high energies, the Landau-Pomeranchuk-Migdal effect and the Ter-Mikaelian effect decrease the Bremsstrahlung cross section noticeably. If you plot the average energy loss divided by the energy, it becomes clear: ![loss_muon](https://user-images.githubusercontent.com/37806666/157478043-7f18d137-e3fe-4158-b5cf-5bc493cc1116.png)

Oh, so one could actually expect an increase in the slope after all. Thank you, that's quite interesting. Also, I have not heard about Ter-Mikaelian effect before, so I learned something new :)

**Comment by pkalaczynski** [comment]
Thank you all for swift replies, I think I'm already satisfied with the answers, so I'll close the issue.
