### ISSUE TITLE
Photoeffect parametrization can cause Arithmetic Exceptions

### ISSUE THREAD

**Issue by Jean1995** [tudo-astroparticlephysics/PROPOSAL#313]
When the Photoeffect parametrization is evaluated, arithmetic exceptions can occur.
While this doesn't seem to be a problem for standalone PROPOSAL, this is a problem within CORSIKA 8, since it catches floating-point exceptions using `feenableexcept(FE_INVALID)`.

Within the photoeffect parametrization, `gamma` is calculated via `1 + (energy - I) / ME;` where `I` is the ionization energy of the K-shell electron. When `energy` get close to `I`, `gamma` becomes 1.
However, this leads to the argument of a `std::sinh` call to become too big, causing the arithmetic exception.

The easiest solution to fix this would be to have our `LowerEnergyLim` not to be `I`, but rather slightly above `I`, for example `1.1*I`. This would avoid that the cross section is evaluated very close to `I`.

**Comment by asandrock** [comment]
This can be solved by the approximation sinh x ~ exp(x)/2 at large values of x.

**Comment by asandrock** [comment]
This can be solved by the approximation sinh x ~ exp(x)/2, which is accurate to 1e-9 for x > 10. Fixed this in PR #314

**Comment by Jean1995** [comment]
fixed in #314
