### ISSUE TITLE
proposal 7 import does not seem to work in Ubuntu 22.04

### ISSUE THREAD

**Issue by shallmann** [tudo-astroparticlephysics/PROPOSAL#327]
Installing proposal via pip (using conan) finishes without obvious problems. However, then there is this error:

```
>>> import proposal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libpython3.9.so.1.0: cannot open shared object file: No such file or directory
```
Any clue how to solve this?

--

This is the conan profile:
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++11
build_type=Release
```

**Comment by maxnoe** [comment]
@shallmann Ubuntu 22.04 comes with python 3.10. Did you build proposal before updating on a previous release? Or how did you install python 3.9?

**Comment by shallmann** [comment]
I was running a (mini)conda environment with python 3.9. Wasn't expecting that this should not work?

However, after your comment, I generated a new conda env with python 3.10 and that works fine thanks @maxnoe

**Comment by maxnoe** [comment]
> I was running a (mini)conda environment with python 3.9. Wasn't expecting that this should not work?

That should work! Was you conda env active? Was pip used from within that conda env?
