### ISSUE TITLE
proposal 6 installation failing on Ubuntu 22 due to log4cplus submodule

### ISSUE THREAD

**Issue by shallmann** [tudo-astroparticlephysics/PROPOSAL#331]
With Ubuntu 22, proposal 6 pip installation fails, because of an incompatible log4cplus submodule version

While one should of course upgrade to newer proposal version, the following step-by-step guide should work to install proposal (eg. tag `6.1.6`) on Ubuntu 22.

- clone the desired version of PROPOSAL 6: `git clone git@github.com:tudo-astroparticlephysics/PROPOSAL.git -b 6.1.6 PROPOSAL6 && cd PROPOSAL6`
- fetch submodules used in PROPOSAL: `git submodule update --init --recursive`
- go to the log4cplus directory: `cd vendor/log4cplus/log4cplus`
- upgrade to a compatible version, `REL_2_0_8` (the `master` requires a c++17 compatible compiler): `git checkout REL_2_0_8`
- fetch the submodules used in (that version of log4cplus) again: `git submodule update --init --recursive`
- go back to the main directory (`cd ../../..`) and run a pip-install: `pip install .`

That should work.

**Comment by Jean1995** [comment]
I have made a release `6.1.8` where this has been fixed, so one can just do `pip install proposal==6.1.8` now.
