### ISSUE TITLE
Vendor dependencies

### ISSUE THREAD

**Issue by MaxNoe** [tudo-astroparticlephysics/PROPOSAL#35]
PROPOSAL has one required dependency: log4cplus >= 2 and gtest is required for the tests.

log4cplus >= 2 is in no major package manager on any of the current distributions.
This should be vendored, gtest should also be build against the current project, not globally.

Two different approaches could be made:

* Add the code to this repository:
  Pro: easy
  Con: bloats history and repository

* Use git submodules
  * Pro: just a submodule
  * Con: not automatically packaged into tar ball by github and requires `--recursive` when cloning.
           First can be dealed with by publishing source tar balls via travis second through Readme.

I would prefer the second path I think. 
Any solution based on cmakes ability to download dependencies should be avoided as then building requires internet connection.

**Comment by sudojan** [comment]
This issue was fixed in pull request #37 and #38.
