### ISSUE TITLE
Restructuture Propagator/Sector/Propagation Utility

### ISSUE THREAD

**Issue by MaxSac** [tudo-astroparticlephysics/PROPOSAL#40]
Propagator is long and not readable. Prefer small and clear methods. Up to now, the Propagator points the particle to the specific sectors, which propagate the particle. This is counter intuitive and the assignment to the sectors and the length to propagate is not useful. This is related to the Border Problem Issue #33.
The Propagator should be restructured and the Propagation Utility should be upgraded, while the Sector becomes redundant.

**Comment by Jean1995** [comment]
![IMG_20200220_155721](https://user-images.githubusercontent.com/15159319/75027818-7a808e00-549f-11ea-8bca-d69628953ad0.jpg)

**Comment by sudojan** [comment]
This is restructured in MR #137

**Comment by sudojan** [comment]
This is done in MR #137
