### ISSUE TITLE
Enable usage of newest pybind11 version

### ISSUE THREAD

**Issue by Jean1995** [tudo-astroparticlephysics/PROPOSAL#43]
At the moment, we are "stuck" with version v2.2.4 of pybind11. If we use a newer version of pybind11 and try to import pyPROPOSAL, the error ``ImportError: generic_type: type "MuMinusDef" does not have a non-default holder type while its base "PROPOSAL::ParticleDef" does`` occurs. This is related to the "issue" https://github.com/pybind/pybind11/issues/1317

**Comment by MaxNoe** [comment]
Strange, in #35 I used the newest release version of pybind11 and got no compilation error.

**Comment by MaxNoe** [comment]
Ah, sorry, its an import time error. It's still an issue, yes.

**Comment by sudojan** [comment]
This was fixed in 582b3db.
