### ISSUE TITLE
More intuitive usage of Vector3D

### ISSUE THREAD

**Issue by Jean1995** [tudo-astroparticlephysics/PROPOSAL#45]
Although completely functional, the Vector3D class in PROPOSAL is not entirely intuitive to use. Users mishandling a Vector3D object may get undesired behaviors. This especially occurs when converting cartesian coordinates to spherical coordinates and vice versa.

Do we need to save both versions of the coordinates in a Vector3D object? If we do, we should ensure that the user doesn't have to call a transformation method (``CalculateCartesianFromSpherical`` or ``CalculateSphericalCoordinates``) before he reads the position. This should be handled automatically by the Vector3D class.

**Comment by MaxNoe** [comment]
Maybe even Switch to eigen instead of refactoring the self made linalg implementation?

**Comment by sudojan** [comment]
Now this Cartesian3D and Spherical3D are in MR #137
