### ISSUE TITLE
Tests for the python bindings

### ISSUE THREAD

**Issue by maxnoe** [tudo-astroparticlephysics/PROPOSAL#46]
Probably connected to #42, as this could be nicely done with a pip installable module and pytest.

Also relevant: #43

**Comment by Jean1995** [comment]
We are now using one travis build to test the pypi installation and pytest to test at least one example script (see for example [this job](https://travis-ci.org/github/tudo-astroparticlephysics/PROPOSAL/jobs/766089711)).

Is this issue solved?
