### ISSUE TITLE
store relevant losses

### ISSUE THREAD

**Issue by sudojan** [tudo-astroparticlephysics/PROPOSAL#71]
There is the option to store just the losses that are inside the detector volume because an experiment is not interested in the secondaries outside of their detector.
But high energetic hadronic cascades can produce muons, that can travel to the detector. Or the muonic tau decays, or the muon pair production.
If these processes occur before the detector they should also be stored.
So the flag should be changed to relevant_losses.

**Comment by Jean1995** [comment]
This is possible after PR #137 by using the queries that are provided by the new Secondaries class. Here, you can filter specific interaction types and/or interactions inside specific geometries to get all losses that are relevant for the user.
